### ISSUE TITLE
python error grabbing tags

### ISSUE THREAD

**Issue by matphillips** [rmrector/service.stinger.notification#4]
Using the 'grab tags' menu option from advanced menu gives following error in logs and nothing is updated:

```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <class 'TypeError'>
  Error Contents: function takes at most 2 arguments (3 given)
  Traceback (most recent call last):
  File "/Users/username/Library/Application Support/Kodi/addons/service.stinger.notification/python/service.py", line 70, in onNotification
  commander.graball_stingertags()
  File "/Users/username/Library/Application Support/Kodi/addons/service.stinger.notification/python/commander.py", line 26, in graball_stingertags
  progress.update(count * 100 / len(movielist), xbmc.getLocalizedString(194), movie['label'])
  TypeError: function takes at most 2 arguments (3 given)
-->End of Python script error report<--
```

MacOS 12.3.1
Kodi 19.4

**Comment by EagleFlyFree** [comment]
It would be nice to fix this issue...
